export default {
    "Barbie": {
        colors: {
            comment : 'Colors',
            primary: '#FF8AD0',
            secondary: '#6C6A6A',
            accent: '#3C3C3C',
            background: '#F8F8F8',
            gradient: '#000000',
        },
        fontFamilies:{
            comment : 'Font Families',
            titles: 'Questrial, sans-serif',
            body:'Questrial, sans-serif'
        },
        fontSizes: {
            comment : 'Font sizes',
            landing: '3rem',
            h1: '2.25rem',
            h2: '1.5rem',
            h3: '1rem'
        },
        padding:{
            comment : 'Paddings',
            p0: '0',
            p1: '0.25rem',
            p2: '0.5rem',
            p3:'0.75rem',
            p4:'1rem',
            p5:'1.25rem',
            p6:'1.5',
            p8:'2rem',
            p10:'2.5rem',
            p12:'3rem',
            p16:'4rem',
            p20:'5rem',
            p24:'6rem',
            p32:'8rem',
            p40:'10rem',
            p48:'12rem',
            p56:'14rem',
            p64:'16rem',
        },
        borders: {
            comment : 'Borders',
            border: 'none',
            hightlight:' none',
            radius: '2rem',
        },
    },
    "C Monochromatic": {
        colors: {
            comment : 'Colors',
            primary: '#000000',
            secondary: '#6C6A6A',
            accent: '#3C3C3C',
            background: '#F4F4F4',
            gradient: '#000000',
        },
        fontFamilies:{
            comment : 'Font Families',
            titles: 'Work Sans,sans-serif',
            body:'Work Sans,sans-serif'
        },
        fontSizes: {
            comment : 'Font sizes',
            landing: '3rem',
            h1: '2.25rem',
            h2: '1.5rem',
            h3: '1rem'
        },
        padding:{
            comment : 'Paddings',
            p0: '0',
            p1: '0.25rem',
            p2: '0.5rem',
            p3:'0.75rem',
            p4:'1rem',
            p5:'1.25rem',
            p6:'1.5',
            p8:'2rem',
            p10:'2.5rem',
            p12:'3rem',
            p16:'4rem',
            p20:'5rem',
            p24:'6rem',
            p32:'8rem',
            p40:'10rem',
            p48:'12rem',
            p56:'14rem',
            p64:'16rem',
        },
        borders: {
            comment : 'Borders',
            border: 'none',
            hightlight:' none',
            radius: '.125rem',
        },
    },
    "Pretty Saumon": {
        colors: {
            comment : 'Colors',
            primary: '#F39289',
            secondary: '#000000',
            accent: '#6C6A6A',
            background: '#F4F4F4',
            gradient: 'linear-gradient(247deg, #F6EA41 -31.78%, #F048C6 183.94%)',
        },
        fontFamilies:{
            comment : 'Font Families',
            titles: 'Work Sans, sans-serif',
            body:'Work Sans, sans-serif'
        },
        fontSizes: {
            comment : 'Font sizes',
            h1: '3.25rem',
            h2: '2.5rem'
        },
        padding:{
            comment : 'Paddings',
            p0: '0',
            p1: '0.25rem',
            p2: '0.5rem',
            p3:'0.75rem',
            p4:'1rem',
            p5:'1.25rem',
            p6:'1.5',
            p8:'2rem',
            p10:'2.5rem',
            p12:'3rem',
            p16:'4rem',
            p20:'5rem',
            p24:'6rem',
            p32:'8rem',
            p40:'10rem',
            p48:'12rem',
            p56:'14rem',
            p64:'16rem',
        },
        borders: {
            comment : 'Borders',
            border: 'none',
            hightlight:' none',
            radius: '.125rem',
        },
    },
    "Blue Night": {
        colors: {
            comment : 'Colors',
            primary: '#ffffff',
            secondary: '#5585FF',
            accent: '#ffffff',
            background: '#040404',
            gradient: 'radial-gradient(50% 50% at 50% 50%, rgba(253, 248, 131, 0.10) 0%, rgba(255, 255, 255, 0.00) 100%)',
        },
        fontFamilies:{
            comment : 'Font Families',
            titles: 'Exo 2, sans-serif',
            body:'Alegreya Sans, sans-serif'
        },
        fontSizes: {
            comment : 'Font sizes',
            h1: '8vw',
            h2: '48px',
            h3: '24px'
        },
        padding:{
            comment : 'Paddings',
            p0: '0',
            p1: '0.25rem',
            p2: '0.5rem',
            p3:'0.75rem',
            p4:'1rem',
            p5:'1.25rem',
            p6:'1.5',
            p8:'2rem',
            p10:'2.5rem',
            p12:'3rem',
            p16:'4rem',
            p20:'5rem',
            p24:'6rem',
            p32:'8rem',
            p40:'10rem',
            p48:'12rem',
            p56:'14rem',
            p64:'16rem',
        },
        borders: {
            comment : 'Borders',
            border: 'none',
            hightlight:' none',
            radius: '.125rem',
        },
    },
    "SpiderMan": {
        colors: {
            comment : 'Colors',
            primary: '#ffffff',
            secondary: '#FCFCFC',
            accent: '#921333',
            background: '#06081A',
        },
        fontFamilies:{
            comment : 'Font Families',
            titles: 'Questrial, sans-serif',
            body: 'Montserrat, sans-serif'
        },
        fontSizes: {
            comment : 'Font sizes',
            landing: '3rem',
            h1: '2.5rem',
            h2: '2rem',
            h3: '1.5rem'
        },
        padding:{
            comment : 'Paddings',
            p0: '0',
            p1: '0.25rem',
            p2: '0.5rem',
            p3:'0.75rem',
            p4:'1rem',
            p5:'1.25rem',
            p6:'1.5',
            p8:'2rem',
            p10:'2.5rem',
            p12:'3rem',
            p16:'4rem',
            p20:'5rem',
            p24:'6rem',
            p32:'8rem',
            p40:'10rem',
            p48:'12rem',
            p56:'14rem',
            p64:'16rem',
        },
        borders: {
            comment : 'Borders',
            border: '1px solid #ffffff',
            hightlight:' 1px solid #921333',
            radius: '.125rem',
        },
    }
};

